version: '3.7'

services:
    db:
        container_name: 'database-flapper'
        image: mysql:5.7
        command: >
            --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
        restart: always
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - TZ=America/Sao_paulo
        volumes:
            - mysql:/var/lib/mysql

    app:
        build: .
        container_name: flapper
        ports:
            - '3000:3000'
        volumes: 
            - .:/usr/app
        links: 
            - db
        depends_on: 
            - db 

volumes:
    mysql:
        driver: local